CREATE DATABASE "create-db-based-on-diagram"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
    
    
CREATE TABLE public.patients
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255),
    date_of_birth date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.medical_histories
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    admitted_at timestamp without time zone NOT NULL,
    patient_id bigint NOT NULL,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT medical_histories_pkey PRIMARY KEY (id),
    CONSTRAINT patient_id FOREIGN KEY (patient_id)
        REFERENCES public.patients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);

CREATE TABLE public.treatments
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    type character varying,
    name character varying(255),
    PRIMARY KEY (id)
);

