CREATE DATABASE "create-db-based-on-diagram"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
    
    
CREATE TABLE public.patients
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255),
    date_of_birth date,
    PRIMARY KEY (id)
);
