/* Database schema to keep the structure of entire database. */

CREATE TABLE animals
(
    id SERIAL PRIMARY KEY,
    name character varying(50),
    date_of_birth date,
    escape_attempts integer,
    neutered boolean,
    weigth_kg double precision
);


/* Modified table*/

CREATE TABLE IF NOT EXISTS public.animals
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 6 MINVALUE 6 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default",
    date_of_birth date,
    escape_attempts integer,
    neutered boolean,
    weigth_kg double precision,
    species text COLLATE pg_catalog."default",
    CONSTRAINT animals_pkey PRIMARY KEY (id)
)
